//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string AppleChar {
            get {
                return ResourceManager.GetString("AppleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string CornerChar {
            get {
                return ResourceManager.GetString("CornerChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string EmptyBlockChar {
            get {
                return ResourceManager.GetString("EmptyBlockChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter [P] to play again or any other key to exit.
        /// </summary>
        internal static string GameOverMessage {
            get {
                return ResourceManager.GetString("GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string HorizontalChar {
            get {
                return ResourceManager.GetString("HorizontalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Lost.
        /// </summary>
        internal static string LostMessage {
            get {
                return ResourceManager.GetString("LostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter [P] to pause the game.
        /// </summary>
        internal static string PauseMessage {
            get {
                return ResourceManager.GetString("PauseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter [R] to resume the game, [S] to change the speed, [D] to change the game size and [P] to disable the bot.
        /// </summary>
        internal static string PauseOptionsDisableBotMessage {
            get {
                return ResourceManager.GetString("PauseOptionsDisableBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter [R] to resume the game, [S] to change the speed, [D] to change the game size and [B] to enable the bot.
        /// </summary>
        internal static string PauseOptionsEnableBotMessage {
            get {
                return ResourceManager.GetString("PauseOptionsEnableBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string SnakeChar {
            get {
                return ResourceManager.GetString("SnakeChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string VerticalChar {
            get {
                return ResourceManager.GetString("VerticalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Won.
        /// </summary>
        internal static string WonMessage {
            get {
                return ResourceManager.GetString("WonMessage", resourceCulture);
            }
        }
    }
}
